services:
  backend:
    build:
      context: ./VisnamPOS
      dockerfile: visnam.pos/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080

  frontend:
    build:
      context: ./VisnamPOS_FE/visnam-pos-fe
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:5000/api
    ports:
      - "3000:80"
    depends_on:
      - backend

